using Aitgmbh.Tapio.Developerapp.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Aitgmbh.Tapio.Developerapp.Web.Scenarios.SampleScenario
{
    [Scenario("sample-scenario", "Sample Module", "/scenario-sample", "src/web/src/app/scenario-sample", "src/web/Scenarios/SampleScenario", "http://tapio.one")]
    [Produces("application/json")]
    [Route("api/[controller]")]
    public sealed class HelloWorldController : Controller
    {
        [HttpGet]
        public ActionResult<string> Welcome()
        {
            return Ok("Hello World from the fancy sample scenario! Btw. this text is generated by the backend 🤓");
        }
    }
}
